### ISSUE TITLE
System.Net.Http.UnsupportedMediaTypeException

### ISSUE THREAD

**Issue by parabola949** [MrRoundRobin/telegram.bot#108]
When the Telegram API is down, the telegram.bot API throws this error:

> Unhandled Exception: System.Net.Http.UnsupportedMediaTypeException: No MediaTypeFormatter is available to read an object of type 'ApiResponse`1' from content with media type 'text/html'.
   at System.Net.Http.HttpContentExtensions.ReadAsAsync[T](HttpContent content, Type type, IEnumerable`1 formatters, IFormatterLogger formatterLogger, CancellationToken cancellationToken)
   at System.Net.Http.HttpContentExtensions.ReadAsAsync[T](HttpContent content, Type type, IEnumerable`1 formatters, IFormatterLogger formatterLogger)
   at System.Net.Http.HttpContentExtensions.ReadAsAsync[T](HttpContent content, IEnumerable`1 formatters)
   at System.Net.Http.HttpContentExtensions.ReadAsAsync[T](HttpContent content)
   at Telegram.Bot.Api.<SendWebRequest>d__78`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Telegram.Bot.Api.<Receive>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__5(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

Because this is being thrown from inside telegram.bot, I am unable to catch (unless I use the AppDomain unhandled exception handling, which I'd prefer not to do for something like that).

**Comment by MrRoundRobin** [comment]
should be resolved with the [`ReceiveError`](https://mrroundrobin.github.io/telegram.bot/html/E_Telegram_Bot_TelegramBotClient_ReceiveError.htm) and [`ApiRequestException`](https://mrroundrobin.github.io/telegram.bot/html/T_Telegram_Bot_Exceptions_ApiRequestException.htm)
