### ISSUE TITLE
System.ArgumentOutOfRangeException in Bot

### ISSUE THREAD

**Issue by delavarimoshen** [MrRoundRobin/telegram.bot#170]
hi
my Bot is Admin in a Supergroup
when i edit a post , throw this Exception 
please fix it

Exception:
System.ArgumentOutOfRangeException was unhandled
Message: An unhandled exception of type 'System.ArgumentOutOfRangeException' occurred in mscorlib.dll
Additional information: Specified argument was out of the range of valid values.

**Comment by MrRoundRobin** [comment]
@delavarimoshen 

i created a separate event for edited messages, cloud you resolve the issue with that?

if not, i need a code snippet to reproduce

**Comment by dedo1911** [comment]
I was about to post the same exception. Basically when a message got edited, something happen and the message received event is not being fired.

This is my full exception:


```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Telegram.Bot.Types.Update.get_Type()
   at CactusBot.Telegram.<ProcessTGUpdate>d__10.MoveNext()

```

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Telegram.Bot.Types.Update.get_Type()
   at Telegram.Bot.Api.OnUpdateReceived(UpdateEventArgs e)
   at Telegram.Bot.Api.<Receive>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by dedo1911** [comment]
Just updated to latest 10.2.0-beta-1 via nuget and the problem is fixed.

**Comment by amastaneh** [comment]
Hi, I have some exception like this with `Telegram.Bot` nuget version=10.4.0 that exception message is `Specified argument was out of the range of valid values.` when try access to update type like `update?.Type.ToString()`

Is it possible the problem still exist in 10.4.0 ?

**Comment by babakx** [comment]
I had same problem. I noticed that I was using the wrong type of controller. You should use API controller (not MVC controller) to properly bind the update parameter. Just look at the example that Robin created for setWebhooks: 
https://github.com/MrRoundRobin/telegram.bot.examples/blob/master/Telegram.Bot.Examples.WebHook/Program.cs

**Comment by hosseinpanahi** [comment]
What about now?! MVC and Web API, they are unified now! and on binding there is error!

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Telegram.Bot.Types.Update.get_Type()
