### ISSUE TITLE
error 400 (bad request)

### ISSUE THREAD

**Issue by jcmag** [MrRoundRobin/telegram.bot#276]
My bot gets a 400 error when he sends a message to a user:

2016-12-08 15:07:22,909 DEBUG [Api] (null) - SendWebRequest: Response status code does not indicate success: 400 (Bad Request).
2016-12-08 15:07:22,940 DEBUG [Api] (null) -   e: System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Telegram.Bot.Api.<SendWebRequest>d__89`1.MoveNext() in D:\Bitbucket\FeedReaderBot\Telegram.Bot2\Api.cs:line 1084

I've contacted Telegram support (I have 1000+ users and it's the first time I have this issue), and they said they always send a description field with the error:

"When you get a 400 error_code, you should also get an error_description field."

Question is: how could I get this error_description?

(I'm using your old Api.cs code, I just added some debug messages in the "catch (HttpRequestException e)" block)

**Comment by jcmag** [comment]
Ah, it seems I should have some info in responseObject, will try that...

**Comment by jcmag** [comment]
responseObject.message says "bad request: reply markup is too long"
all is clear now :)
