### ISSUE TITLE
exception in GetUpdates

### ISSUE THREAD

**Issue by appa1303** [MrRoundRobin/telegram.bot#35]
Hi,

I am using the last NuGet package 2.0.0.248
After long period of calling GetUpdates  in a loop (a few hours)
the following exception is sometimes thrown (from GetUpdates):

System.Net.Http.UnsupportedMediaTypeException: No MediaTypeFormatter is available to read an object of type 'ApiResponse\`1' from content with media type 'text/html'.
at System.Net.Http.HttpContentExtensions.ReadAsAsync\[T](HttpContent content, Type type, IEnumerable\`1 formatters, IFormatterLogger formatterLogger, CancellationToken cancellationToken)
at System.Net.Http.HttpContentExtensions.ReadAsAsync\[T] (HttpContent content, Type type, IEnumerable1 formatters, IFormatterLogger formatterLogger)
at System.Net.Http.HttpContentExtensions.ReadAsAsync\[T] (HttpContent content, IEnumerable\`1 formatters)
at System.Net.Http.HttpContentExtensions.ReadAsAsync\[T] (HttpContent content)
at Telegram.Bot.Api.<SendWebRequest>d__24\`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Telegram.Bot.Api.<GetUpdates>d__4.MoveNext()

**Comment by anubhavranjan** [comment]
Even I am getting the same error. Any help?
I am using the latest version.

   at System.Net.Http.HttpContentExtensions.ReadAsAsync[T](HttpContent content, Type type, IEnumerable`1 formatters, IFormatterLogger formatterLogger, CancellationToken cancellationToken)
   at System.Net.Http.HttpContentExtensions.ReadAsAsync[T](HttpContent content, Type type, IEnumerable`1 formatters, IFormatterLogger formatterLogger)
   at System.Net.Http.HttpContentExtensions.ReadAsAsync[T](HttpContent content, IEnumerable`1 formatters)
   at Telegram.Bot.Api.<SendWebRequest>d__45`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TvShowsReminder.d__1.MoveNext()

**Comment by deinemutterduspasst** [comment]
please update to the new version! all problems are solved!
