### ISSUE TITLE
Unhandled Exception in GetUpdates

### ISSUE THREAD

**Issue by inornos** [MrRoundRobin/telegram.bot#45]
Encountered exception in GetUpdates function.

Unhandled Exception: System.AggregateException: One or more errors occurred. ---
> System.Net.Http.HttpRequestException: An error occurred while sending the requ
est. ---> System.Net.WebException: The underlying connection was closed: The con
nection was closed unexpectedly.
    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
    at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
    --- End of inner exception stack trace ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAw
aiter.GetResult()
    at Telegram.Bot.Api.<SendRequest>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAw
aiter.GetResult()
    at Telegram.Bot.Api.<SendWebRequest>d__26`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAw
aiter.GetResult()
    at Telegram.Bot.Api.<GetUpdates>d__5.MoveNext()
    --- End of inner exception stack trace ---
    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotifica
tion)
    at System.Threading.Tasks.Task`1.get_Result()
    at SmartTeleBot.Program.Main()

Code:
```csharp
while (true)
{
	try
	{
		updates = bot.GetUpdates(offset);
	}
	catch { }

	try
	{
		// encountered error in 'updates.Result'
		foreach (Telegram.Bot.Types.Update update in updates.Result)
		{
			// Do some work
		}
	}
	catch (Exception ex)
	{
		// Error handling.
	}
}
```

**Comment by MrRoundRobin** [comment]
Hi,

in an AggregateException the important parts is the innerException.

it looks linke there was problem withe the internet connection "The underlying connection was closed: The connection was closed unexpectedly"

**Comment by inornos** [comment]
Thank you
