### ISSUE TITLE
(CS1701)

### ISSUE THREAD

**Issue by Rusmlov** [MrRoundRobin/telegram.bot#66]
Hey!
Thanks for your amazing work on telegram.bot

I installed telegram.bot as NuGet Package and i've got this waring when i try to compile:
Assuming assembly reference `Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' matches assembly `Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. You may need to supply runtime policy (CS1701)

it still compile but when i try to execute i get this:
Unhandled Exception: System.AggregateException: One or more errors occurred. ---

System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter..ctor()
at System.Net.Http.Formatting.JsonMediaTypeFormatter..ctor()
at System.Net.Http.Formatting.MediaTypeFormatterCollection.CreateDefaultFormatters()
at System.Net.Http.HttpContentExtensions.get_DefaultMediaTypeFormatterCollection()
at System.Net.Http.HttpContentExtensions.ReadAsAsyncT
at Telegram.Bot.Api.d__451.MoveNext()
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task.ThrowIfExceptional(BooleanincludeTaskCanceled Exceptions)
at System.Threading.Tasks.Task1.GetResultCore(Boolean waitCompletionNotification)
at System.Threading.Tasks.Task`1.get_Result()
at teste3.MainClass.foreverCheckUpdates()
at teste3.MainClass.Main(String[] args)

I've tried to solve it by myself but i've not had sucess.
Thanks.

**Comment by Rusmlov** [comment]
I solved it.
I just had to add a file called app.config with the following content:
<?xml version="1.0" encoding="UTF-8" ?>
<configuration>
	<runtime>
		<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
			<dependentAssembly>
				<assemblyIdentity name="Newtonsoft.Json"  publicKeyToken="30AD4FE6B2A6AEED" culture="neutral"/>
				<bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="7.0.0.0"/>
		</dependentAssembly>
		</assemblyBinding>
	</runtime>
</configuration>

and it worked.
Thanks.

**Comment by MrRoundRobin** [comment]
Hi,

this should be resolved in the next version, working on inline bot support ;)
