### ISSUE TITLE
ApiRequestException never catch exceptions

### ISSUE THREAD

**Issue by Bouki6** [MrRoundRobin/telegram.bot#85]
Hello.
at first let me thank you for your excellent API. I use many API's but in my opinion your API is the best. anyway. there is only one problem and its error handling. please take a look at my code:
```
        public bool SendText()
        {
            var sw = Stopwatch.StartNew();

            try
            {
                var textMessage = (TextMTMessage)Message;
                var message = Bot.SendTextMessage(textMessage.Destination.Telegram.ID, textMessage.RequiredParameters.Content).Result;
                MessageID = message.MessageId;

                Success();
                Log.Trace("sending message successfully completed.", sw.Elapsed.TotalMilliseconds);
                return true;
            }
            catch(ApiRequestException ex)
            {
                Failed();
                Log.Fatal(ex.ToString(), sw.Elapsed.TotalMilliseconds);
                return false;
            }
            catch (Exception ex)
            {
                Failed();
                Log.Fatal(ex.ToString(), sw.Elapsed.TotalMilliseconds);
                return false;
            }
        }
```
the problem is `ApiRequestException `never catch exceptions!. always an `AggregateException `thrown. i take a look to inner exceptions and i found a real exception. here an example:
```
[FATAL];[2016-02-10 11:51:07,295];[18];[ViaTelegram.SendText line:69];[898.3725];[];[(Message: System.AggregateException: One or more errors occurred. ---> Telegram.Bot.Types.ApiRequestException: [Error]: Bad Request: Message text is empty
   at Telegram.Bot.Api.<SendWebRequest>d__78`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at TelegramGateWay.ViaTelegram.SendText() in C:\Users\Admin\Desktop\Projects\SimSend_SVN\trunk\TelegramGateWay\TelegramGateWay\Intermediate\ViaTelegram.cs:line 52
---> (Inner Exception #0) Telegram.Bot.Types.ApiRequestException: [Error]: Bad Request: Message text is empty
   at Telegram.Bot.Api.<SendWebRequest>d__78`1.MoveNext()<---
)]
```
thank you

**Comment by MrRoundRobin** [comment]
I think it's because you don't use `await`... can you try it with `await` rather than `Task.Result`?

**Comment by Bouki6** [comment]
Hello.
at first let me thank you for fixing the 403 error in such a short time. i know you are so busy. 
> I think it's because you don't use await... can you try it with await rather than Task.Result?
you were right about that. i used the await and catch the exceptions. here is my code:
```
            try
            {
                var task = new Api("bot token").SendTextMessage(66617958, "Test Message");
                if (await Task.WhenAny(task, Task.Delay(1000)) == task)
                {
                    var message = await task;
                    MessageBox.Show(JsonConvert.SerializeObject(message));
                }
                else
                {
                    MessageBox.Show(JsonConvert.SerializeObject("time out"));
                }
            }
            catch (ApiRequestException ex)
            {
                MessageBox.Show(ex.Message.ToString());
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message.ToString());
            }
```
i thought it might be useful for others.
Thank you again dear Robin Müller and i hope successfully present your bachelor thesis.
sincerely  M.Montazeri.
